publish_to: none

name: using_words
version: 0.0.1

description: This is a sample project which uses the 'words' lint ruleset.

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  words: ^2.0.0+1