name: words
description: Collection of Dart linter rules used in projects of WordCollector.
homepage: https://github.com/wordcollector/words
repository: https://github.com/wordcollector/words
issue_tracker: https://github.com/wordcollector/words/issues
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'