publish_to: https://pub.dev

name: words
version: 0.0.2+1

description: >-
  A curated collection of lints for use by Dart packages to ensure
  higher program safety and to promote best practices, selected and
  maintained by WordCollector.

homepage: https://github.com/wordcollector/words
repository: https://github.com/wordcollector/words
issue_tracker: https://github.com/wordcollector/words/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
