name: words

version: 0.0.2
description: >-
  Collection of Dart linter rules used in projects of WordCollector,
  ensuring that code packages and programs are written to the highest
  standard possible.

homepage: https://github.com/wordcollector/words
repository: https://github.com/wordcollector/words
issue_tracker: https://github.com/wordcollector/words/issues

environment:
  sdk: '>=2.12.0 <3.0.0'